# Generated by Django 4.1.1 on 2023-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharastra', 'Maharastra'), ('Bihar', 'Bihar')], max_length=80),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=80),
        ),
    ]
