# Generated by Django 4.1.1 on 2023-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_state_alter_orderplaced_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Maharastra', 'Maharastra')], max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('BW', 'BottomWear'), ('TW', 'TopWear'), ('L', 'Laptop')], max_length=80),
        ),
    ]
